# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: false

install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "stringr", "knitr"))'

script:
  - Rscript -e 'devtools::install_deps(".")'
  - Rscript -e 'devtools::check(".")'
  - R CMD INSTALL .